---
bert_classifier:
  SEED : 42
  N_EPOCHS : 10
  PATIENCE : 5
  ACCUM_ITER : null
  WARMUP_STEPS : 0
  EVAL_EVERY_N_EPOCH : 1
  N_TRAIN_SAMPLES : 16384
  N_VAL_SAMPLES : null
  N_TEST_SAMPLES: null
  DATA_PATH : "../../data/"
  LOGGER_NAME : "BC"
  MODEL_NAME : "bert-base-uncased"
  TRAIN_BATCH_SIZE : 64
  TEST_BATCH_SIZE : 512
